compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "bootstrap@4.6.2":
    peerDependenciesMeta:
      popper.js:
        optional: true

yarnPath: .yarn/releases/yarn-4.17.1.cjs
